// Minimal IPA helper for the verbs shown in the app.
// Goal: give learners an at-a-glance pronunciation guide that fits the existing UI.

const IPA_DICT = {
  // AAA (same form)
  bet: 'bɛt',
  bid: 'bɪd',
  broadcast: 'ˈbrɔːdkæst',
  burst: 'bɜːrst',
  cast: 'kæst',
  cost: 'kɔːst',
  cut: 'kʌt',
  fit: 'fɪt',
  forecast: 'ˈfɔːrkæst',
  hit: 'hɪt',
  hurt: 'hɜːrt',
  input: 'ˈɪnpʊt',
  knit: 'nɪt',
  let: 'lɛt',
  output: 'ˈaʊtpʊt',
  put: 'pʊt',
  quit: 'kwɪt',
  read: 'riːd',
  rid: 'rɪd',
  set: 'sɛt',
  shed: 'ʃɛd',
  shut: 'ʃʌt',
  slit: 'slɪt',
  spread: 'sprɛd',
  sweat: 'swɛt',
  thrust: 'θrʌst',
  upset: 'ʌpˈsɛt',
  wet: 'wɛt',

  // ABA
  become: 'bɪˈkʌm',
  became: 'bɪˈkeɪm',
  come: 'kʌm',
  came: 'keɪm',
  run: 'rʌn',
  ran: 'ræn',
  overcome: 'ˌoʊvərˈkʌm',
  overcame: 'ˌoʊvərˈkeɪm',

  // ABB (incl. groups)
  bend: 'bɛnd',
  bent: 'bɛnt',
  build: 'bɪld',
  built: 'bɪlt',
  burn: 'bɜːrn',
  burned: 'bɜːrnd',
  burnt: 'bɜːrnt',
  creep: 'kriːp',
  crept: 'krɛpt',
  deal: 'diːl',
  dealt: 'dɛlt',
  dream: 'driːm',
  dreamed: 'driːmd',
  dreamt: 'drɛmt',
  feel: 'fiːl',
  felt: 'fɛlt',
  keep: 'kiːp',
  kept: 'kɛpt',
  leave: 'liːv',
  left: 'lɛft',
  lend: 'lɛnd',
  lent: 'lɛnt',
  light: 'laɪt',
  lit: 'lɪt',
  lose: 'luːz',
  lost: 'lɔːst',
  mean: 'miːn',
  meant: 'mɛnt',
  meet: 'miːt',
  met: 'mɛt',
  send: 'sɛnd',
  sent: 'sɛnt',
  shoot: 'ʃuːt',
  shot: 'ʃɑːt',
  sit: 'sɪt',
  sat: 'sæt',
  sleep: 'sliːp',
  slept: 'slɛpt',
  spend: 'spɛnd',
  spent: 'spɛnt',
  sweep: 'swiːp',
  swept: 'swɛpt',
  weep: 'wiːp',
  wept: 'wɛpt',

  bring: 'brɪŋ',
  brought: 'brɔːt',
  buy: 'baɪ',
  bought: 'bɔːt',
  catch: 'kætʃ',
  caught: 'kɔːt',
  fight: 'faɪt',
  fought: 'fɔːt',
  seek: 'siːk',
  sought: 'sɔːt',
  teach: 'tiːtʃ',
  taught: 'tɔːt',
  think: 'θɪŋk',
  thought: 'θɔːt',

  lay: 'leɪ',
  laid: 'leɪd',
  pay: 'peɪ',
  paid: 'peɪd',
  say: 'seɪ',
  said: 'sɛd',

  dig: 'dɪɡ',
  dug: 'dʌɡ',
  stick: 'stɪk',
  stuck: 'stʌk',
  sting: 'stɪŋ',
  stung: 'stʌŋ',
  strike: 'straɪk',
  struck: 'strʌk',
  swing: 'swɪŋ',
  swung: 'swʌŋ',
  hang: 'hæŋ',
  hung: 'hʌŋ',

  // ABC
  begin: 'bɪˈɡɪn',
  began: 'bɪˈɡæn',
  begun: 'bɪˈɡʌn',
  drink: 'drɪŋk',
  drank: 'dræŋk',
  drunk: 'drʌŋk',
  ring: 'rɪŋ',
  rang: 'ræŋ',
  rung: 'rʌŋ',
  shrink: 'ʃrɪŋk',
  shrank: 'ʃræŋk',
  shrunk: 'ʃrʌŋk',
  sing: 'sɪŋ',
  sang: 'sæŋ',
  sung: 'sʌŋ',
  sink: 'sɪŋk',
  sank: 'sæŋk',
  sunk: 'sʌŋk',
  stink: 'stɪŋk',
  stank: 'stæŋk',
  stunk: 'stʌŋk',
  swim: 'swɪm',
  swam: 'swæm',
  swum: 'swʌm',

  bite: 'baɪt',
  bit: 'bɪt',
  bitten: 'ˈbɪtən',
  break: 'breɪk',
  broke: 'broʊk',
  broken: 'ˈbroʊkən',
  choose: 'tʃuːz',
  chose: 'tʃoʊz',
  chosen: 'ˈtʃoʊzən',
  drive: 'draɪv',
  drove: 'droʊv',
  driven: 'ˈdrɪvən',
  eat: 'iːt',
  ate: 'eɪt',
  eaten: 'ˈiːtən',
  fall: 'fɔːl',
  fell: 'fɛl',
  fallen: 'ˈfɔːlən',
  fly: 'flaɪ',
  flew: 'fluː',
  flown: 'floʊn',
  forbid: 'fərˈbɪd',
  forbade: 'fərˈbeɪd',
  forbidden: 'fərˈbɪdən',
  forget: 'fərˈɡɛt',
  forgot: 'fərˈɡɑːt',
  forgotten: 'fərˈɡɑːtən',
  forgive: 'fərˈɡɪv',
  forgave: 'fərˈɡeɪv',
  forgiven: 'fərˈɡɪvən',
  freeze: 'friːz',
  froze: 'froʊz',
  frozen: 'ˈfroʊzən',
  give: 'ɡɪv',
  gave: 'ɡeɪv',
  given: 'ˈɡɪvən',
  go: 'ɡoʊ',
  went: 'wɛnt',
  gone: 'ɡɔːn',
  grow: 'ɡroʊ',
  grew: 'ɡruː',
  grown: 'ɡroʊn',
  hide: 'haɪd',
  hid: 'hɪd',
  hidden: 'ˈhɪdən',
  know: 'noʊ',
  knew: 'nuː',
  known: 'noʊn',
  lie: 'laɪ',
  lain: 'leɪn',
  ride: 'raɪd',
  rode: 'roʊd',
  ridden: 'ˈrɪdən',
  rise: 'raɪz',
  rose: 'roʊz',
  risen: 'ˈrɪzən',
  see: 'siː',
  saw: 'sɔː',
  seen: 'siːn',
  show: 'ʃoʊ',
  showed: 'ʃoʊd',
  shown: 'ʃoʊn',
  tear: 'tɛr',
  tore: 'tɔːr',
  torn: 'tɔːrn',
  wake: 'weɪk',
  woke: 'woʊk',
  woken: 'ˈwoʊkən',
  wear: 'wɛr',
  wore: 'wɔːr',
  worn: 'wɔːrn',
  write: 'raɪt',
  wrote: 'roʊt',
  written: 'ˈrɪtən',

  speak: 'spiːk',
  spoke: 'spoʊk',
  spoken: 'ˈspoʊkən',
  steal: 'stiːl',
  stole: 'stoʊl',
  stolen: 'ˈstoʊlən',
  throw: 'θroʊ',
  threw: 'θruː',
  thrown: 'θroʊn',
  shake: 'ʃeɪk',
  shook: 'ʃʊk',
  shaken: 'ˈʃeɪkən',
  take: 'teɪk',
  took: 'tʊk',
  taken: 'ˈteɪkən',
};

function normalizeWord(word) {
  return String(word ?? '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z']/g, '');
}

export function ipaForWord(word) {
  const key = normalizeWord(word);
  if (!key) return '';

  // Handle the one ambiguous collision we have: "lay" can be from "lie" (lay/lain)
  // or from "lay" (laid). In the UI we show raw strings; we keep default lay=leɪ.
  // If you ever want disambiguation, pass exact keys yourself.

  return IPA_DICT[key] || '';
}

export function formatIPA(word) {
  const ipa = ipaForWord(word);
  return ipa ? `/${ipa}/` : '';
}

export function formatIPATriplet(words) {
  const [a, b, c] = Array.isArray(words) ? words : [];
  const ia = formatIPA(a);
  const ib = formatIPA(b);
  const ic = formatIPA(c);

  if (!ia && !ib && !ic) return '';
  return [ia || a || '', ib || b || '', ic || c || ''].filter(Boolean).join('  ·  ');
}
